[package]
name = "generators"
version = "0.3.0"
authors = ["Huon Wilson <dbau.pp@gmail.com>"]
edition = "2018"

[dependencies]
primal-slowsieve = { path = "../primal-slowsieve", version = "0.3" }
primal-check = { path = "../primal-check", version = "0.3" }
